CREATE DATABASE VIACEP;

CREATE TABLE ENDERECO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CEP VARCHAR NOT NULL,
    LOGRADOURO VARCHAR(100) NULL,
    COMPLEMENTO VARCHAR(100) NULL,
    BAIRRO VARCHAR(100) NULL,
    LOCALIDADE VARCHAR(30) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    IBGE INT NULL UNSIGNED ,
    GIA INT UNSIGNED,
    DDD INT UNSIGNED,
    SIAFI INT UNSIGNED  NULL
)ENGINE=INNODB;


-- Algumas FIEDLS estão como VARCHAR, pois contem 0 a esquerda e alguns tipos de dados como o INT o ignoram 